apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance 
  namespace: openshift-logging 
spec:
  # serviceAccountName: <service_account_name> 
  outputs:
    - name: splunk-receiver 
      secret:
        name: vector-splunk-secret 
      type: splunk 
      url: https://prd-p-8hq1p.splunkcloud.com:8088
      tls:
        insecureSkipVerify: true
  pipelines: 
    - inputRefs:
        # - application
        # - infrastructure
        - audit
      name: 
      outputRefs:
        - splunk-receiver